<script type="text/javascript" src="{{ asset('js/slider-jquery.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/slider-styleswitcher.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/slider-pace.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/slider-retina-1.1.0.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/slider-modernizr.custom.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/slider-jquery.slimmenu.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/slider-mb.bgndGallery.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/slider-jquery.bxslider.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/slider-jquery.easing.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/slider-jquery.custombox.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/slider-jquery.colorbox.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/slider-jquery.transit.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/slider-jquery.isotope.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/slider-jquery.masonry.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/slider-jquery.fitvids.js') }}"></script>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>
<script type="text/javascript" src="{{ asset('js/slider-gmaps.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/slider-contact.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/slider-template.js') }}"></script>
